language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
  - 4

# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test

after_success:
  - npm run coveralls