language:
  node_js
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
  - 4
install:
  - npm i
  - npm i -g istanbul
  - npm i -g codecov
script:
  - npm run test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov